# src/main/resources/application-private.yml
app:
  allowed-origins: "http://localhost:${server.port}"  # when testing cors requests, remember to change this to the correct origin

spring:
  thymeleaf:
    cache: false