# --------------------------------------
# APP
# --------------------------------------
app:
  name: crawler
  content-base-url: ${CONTENT_BASE_URL}
  static-base-url: ${STATIC_BASE_URL}
  allowed-origins: ${ALLOWED_ORIGINS}

  content-storage: s3://pro-home-with-soul-es-content
  images-storage: s3://pro-home-with-soul-es-images
  static-resources-storage: s3://pro-home-with-soul-es-static-resources

  db:
    url: jdbc:postgresql://localhost:5432/postgres?user=admin&password=1234
