# --------------------------------------
# APP
# --------------------------------------
app:
  name: crawler
  base-path: /crawler
  base-url: http://localhost:8080/crawler
  allowed-origins: ${ALLOWED_ORIGINS}

  db:
    url: jdbc:postgresql://localhost:5432/postgres?user=admin&password=1234
