# --------------------------------------
# APP
# --------------------------------------
app:
  name: crawler
  content-base-url: ${CONTENT_BASE_URL:https://www.casaconalma.com/}
  images-base-url: ${IMAGES_BASE_URL:https://images.casaconalma.com/}
  static-resources-base-url: ${STATIC_RESOURCES_BASE_URL:https://static-resources.casaconalma.com/}
  allowed-origins: ${ALLOWED_ORIGINS}

  content-storage: s3://pro-home-with-soul-es-content
  images-storage: s3://pro-home-with-soul-es-images
  static-resources-storage: s3://pro-home-with-soul-es-static-resources

  db:
    url: jdbc:postgresql://localhost:5432/postgres?user=admin&password=1234
