# --------------------------------------
# APP
# --------------------------------------
app:
  name: crawler
  content-base-url: ${CONTENT_BASE_URL}
  static-base-url: ${STATIC_BASE_URL}
  allowed-origins: ${ALLOWED_ORIGINS}

  db:
    url: jdbc:postgresql://localhost:5432/postgres?user=admin&password=1234
