# src/main/resources/application-private.yml
app:
#  content-storage: file:///Users/jcortes/workspace/personal/crawler/publish-bucket/content
#  images-storage: file:///Users/jcortes/workspace/personal/crawler/publish-bucket/images
#  static-resources-storage: file:///Users/jcortes/workspace/personal/crawler/publish-bucket/static-resource
  content-storage: s3://content-df0e2f8
  images-storage: s3://images-fd7a7c1
  static-resources-storage: s3://static-resources-e5c735d
#  content-base-url: http://localhost:8083/
#  images-base-url: http://localhost:8083/images/
#  static-resources-base-url: http://localhost:8083/static/
  content-base-url: https://www.casaconalma.com/
  images-base-url: https://images.casaconalma.com/
  static-resources-base-url: https://static-resources.casaconalma.com/
  allowed-origins: "http://localhost:${server.port}"  # when testing cors requests, remember to change this to the correct origin
