server:
  port: 8083
  forward-headers-strategy: FRAMEWORK
  compression:
    enabled: true
    min-response-size: 1024
    mime-types: text/html, text/xml, text/plain, text/css, text/javascript, application/javascript, application/json

# --------------------------------------
# SPRING
# --------------------------------------
spring:
  application:
    name: ${app.name}

  datasource:
    url: ${app.db.url}
    hikari:
      maximum-pool-size: 10
      max-lifetime: 31000
      idle-timeout: 28000
      keep-alive-time: 30000
      minimum-idle: 0

  flyway:
    baseline-version: 1
    enabled: true
    locations: classpath:db
    schemas: deco
    validate-on-migrate: true
    baseline-on-migrate: true

info:
  app:
    name: ${spring.application.name}
