# src/main/resources/application-private.yml
app:
  content-storage: file:///Users/jcortes/workspace/personal/crawler/publish-bucket/content
  images-storage: file:///Users/jcortes/workspace/personal/crawler/publish-bucket/images
  static-resources-storage: file:///Users/jcortes/workspace/personal/crawler/publish-bucket/static-resource
#  content-storage: s3://www.casaconalma.com
#  images-storage: s3://www.casaconalma.com
#  static-resources-storage: s3://www.casaconalma.com
  content-base-url: http://localhost:8083/
  images-base-url: http://localhost:8083/images/
  static-resources-base-url: http://localhost:8083/static/
#  content-base-url: https://www.casaconalma.com/
#  images-base-url: https://www.casaconalma.com/images/
#  static-resources-base-url: https://www.casaconalma.com/static/
  allowed-origins: "http://localhost:${server.port}"  # when testing cors requests, remember to change this to the correct origin
