services:
#    postgres:
#        image: postgres:16.4-alpine3.20
#        environment:
#            POSTGRES_USER: admin
#            POSTGRES_PASSWORD: 1234
#        ports:
#            - '5432:5432'
#        networks:
#            - crawler

    pgvector:
        image: pgvector/pgvector:pg16
        environment:
            POSTGRES_HOST: localhost
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: 1234
        ports:
            - '5432:5432'
        networks:
            - crawler

networks:
    crawler:
        name: crawler-dev

volumes:
    postgres-dev-data: